### PR TITLE
storage: retain debond end time when converting genesis

### PR DESCRIPTION
**Pull request by pro-wh**
we've been entering them as all zero

### CODE REVIEW

**Review by Andrew7234 — APPROVED** [review]

**Review by mitjat — APPROVED** [review]
:pray:

**Comment by pro-wh** [comment]
oh do I need to rebuild the caches again

**Comment by pro-wh** [comment]
but why did the analysis succeed if it would have been missing the right cache?

**Comment by pro-wh** [comment]
I guess that's just nexus's style, if one analyzer fails, the rest continues fine, even if the rest is 0 other analyzers

**Pull request merged**
